FROM python:2.7-jessie
RUN apt-get update && apt-get install -y postgresql
ENV PYTHONUNBUFFERED 1
RUN mkdir /frontier
WORKDIR /frontier
COPY ./ /frontier
RUN pip install -r requirements.txt
RUN python manage.py collectstatic --noinput --settings=frontier.settings.prod
CMD python manage.py runserver 0.0.0.0:$PORT
