# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 11:05
from __future__ import unicode_literals

import business.models
import django.contrib.auth.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.crypto
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('token', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storytime', models.TextField(null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('type', models.CharField(choices=[(b'administrator', b'administrator'), (b'candidate', b'candidate'), ('hiring manager', 'hiring manager')], max_length=16, verbose_name='type')),
                ('username', models.CharField(default=django.utils.crypto.get_random_string, max_length=64, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storytime', models.TextField(null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('code', models.CharField(default=business.models.get_invite_code, max_length=16, unique=True, verbose_name='code')),
                ('state', models.CharField(default=b'pending', max_length=20, verbose_name='state')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
            ],
            options={
                'verbose_name': 'Administrator',
                'proxy': True,
                'verbose_name_plural': 'Administrators',
                'indexes': [],
            },
            bases=('business.baseuser',),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
            ],
            options={
                'verbose_name': 'Candidate',
                'proxy': True,
                'verbose_name_plural': 'Candidates',
                'indexes': [],
            },
            bases=('business.baseuser',),
        ),
        migrations.CreateModel(
            name='HiringManager',
            fields=[
            ],
            options={
                'verbose_name': 'Hiring Manager',
                'proxy': True,
                'verbose_name_plural': 'Hiring Managers',
                'indexes': [],
            },
            bases=('business.baseuser',),
        ),
        migrations.AddField(
            model_name='invite',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=business.models.Candidate, to='business.Candidate'),
        ),
    ]
