# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 16:29
from __future__ import unicode_literals

import business.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey', '0001_initial'),
        ('business', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlink',
            name='survey_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='survey.SurveyResponse'),
        ),
        migrations.AddField(
            model_name='loginlink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.Company'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('business.user',),
            managers=[
                ('objects', business.models.AdministratorManager()),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('business.user',),
            managers=[
                ('objects', business.models.ApplicantManager()),
            ],
        ),
        migrations.CreateModel(
            name='HiringManager',
            fields=[
            ],
            options={
                'verbose_name': 'Hiring Manager',
                'proxy': True,
                'verbose_name_plural': 'Hiring Managers',
                'indexes': [],
            },
            bases=('business.user',),
            managers=[
                ('objects', business.models.HiringManagerManager()),
            ],
        ),
    ]
