# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20180306_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='invite_template',
            new_name='invitation_template',
        ),
    ]
