# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20180319_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regularuser',
            options={'verbose_name': 'Regular User', 'verbose_name_plural': 'Regular Users'},
        ),
    ]
