# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20180311_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlink',
            name='password',
            field=models.CharField(default=django.utils.crypto.get_random_string, max_length=16),
        ),
    ]
