# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20180306_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='invitation_template',
        ),
    ]
