# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0002_auto_20180316_0914'),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyinvitation',
            name='hiring_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='business.HiringManager'),
        ),
        migrations.AddField(
            model_name='surveyinvitation',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='survey.Survey'),
        ),
        migrations.AddField(
            model_name='survey',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='survey.Job'),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.Survey'),
        ),
        migrations.AddField(
            model_name='question',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.QuestionTemplate'),
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='business.Company'),
        ),
        migrations.AddField(
            model_name='job',
            name='hiring_managers',
            field=models.ManyToManyField(related_name='jobs', to='business.HiringManager'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='survey_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.SurveyResponse'),
        ),
        migrations.AlterUniqueTogether(
            name='surveyresponse',
            unique_together=set([('user', 'survey')]),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('survey', 'segment', 'index')]),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('survey_response', 'question')]),
        ),
    ]
