# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 09:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20180319_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hard_skills',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='soft_skills',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
