# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 23:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0002_auto_20180311_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyinvitation',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In-progress'), ('success', 'success'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='surveyresponse',
            unique_together=set([('user', 'survey')]),
        ),
    ]
