# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 00:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20180311_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyinvitation',
            options={'verbose_name': 'Survey Invitation', 'verbose_name_plural': 'Survey Invitations'},
        ),
        migrations.AlterField(
            model_name='question',
            name='context',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='questiontemplate',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='questiontemplate',
            name='type',
            field=models.CharField(choices=[('multi_choice_multi_select', 'Multiple Choice Multiple Select'), ('multi_choice_single_select', 'Multiple Choice Single Select'), ('open_ended_paragraph', 'Open-ended Paragraph'), ('open_ended_multi_fields', 'Open-ended Multiple Fields'), ('reorder', 'Reorder'), ('drag_drop', 'Drag & Drop'), ('type_ahead', 'Type Ahead'), ('dropdown', 'Dropdown'), ('rank_order_table', 'Rank Order Table'), ('rank_order_matrix', 'Rank Order Matrix')], max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('survey_response', 'question')]),
        ),
    ]
