# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20180322_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='hiring_managers',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='business.HiringManager'),
        ),
    ]
