# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20180312_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('expired', 'Expired')], default='pending', max_length=16),
        ),
    ]
