# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0002_auto_20180306_1509'),
        ('survey', '0001_initial'),
        ('invite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='hiring_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='business.HiringManager'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='survey.Survey'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='invite.InvitationTemplate'),
        ),
    ]
