# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_remove_company_invitation_template'),
        ('invite', '0002_auto_20180306_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='template',
        ),
        migrations.DeleteModel(
            name='InvitationTemplate',
        ),
    ]
